### PR TITLE
[Feature]Add missing associated user data to the session

### PR DESCRIPTION
**Pull request by osmszk**
### WHY are these changes introduced?
I wanted to get associatedUserId after user authentification using koa-shopiy-auth, but I could not find it in the session.
A lot of Shopify App beginner-developers (including me) use this approach for user authentification, because Shopify introduces that way in the [tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react). 

Also, this is same as this PR https://github.com/Shopify/quilt/pull/1542 .

### WHAT is this pull request doing?

Add associated user data and scope to the session.

This is particularly useful for determining the currently authenticated user in [online access mode](https://shopify.dev/concepts/about-apis/authentication#api-access-modes).

See also: [Authenticate With OAuth Docs](https://shopify.dev/tutorials/authenticate-with-oauth#step-3-confirm-installation)

## Type of change

- [ ] Patch: Bug (non-breaking change which fixes an issue)
- [x] Minor: New feature (non-breaking change which adds functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have added a changelog entry, prefixed by the type of change noted above
- [ ] I have added/updated tests for this change

### CODE REVIEW

**Review by paulomarg — APPROVED** [review]
Thank you for making this change! Code-wise I see it's the same change as before so I will approve it. 

@TheMallen, could I trouble you for your thoughts, as requested by @tanema in the [original PR](https://github.com/Shopify/quilt/pull/1542#issuecomment-658184261)?

**Review by tanema — APPROVED** [review]
🥇

**Comment by ulybu** [comment]
Hi guys, could one of you confirm this is not out yet? Currently can't find user information on my session

**Comment by konrain** [comment]
@mkevinosullivan Hi kevin, how would I access the shop owners email in afterAuth

`const { shop, accessToken } = ctx.state.shopify`
// need email here

I also have "accessMode: 'offline'"  if that makes a difference

**Pull request merged**
